version: '3'
services:
  web:
    image: nginx
  db:
    image: mysql
    ports:
    - "3000:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=Capgemini123
    - MYSQL_USER=user1
    - MYSQL_PASSWORD=capgemini
    - MYSQL_DATABASE=mufg